Fix browsers and teasers
fourkitchens/sous-drupal-distro pull request #27
Opened 2021-03-15 00:34 UTC by callinmullaney

### Purpose:
-

2021-03-19 20:05 UTC, callinmullaney commented on config/install/core.entity_form_display.node.frontpage.default.yml
> -  promote:
Hiding these options from the form display. 

1. Promoting doesn't make sense in this context. Scenario's where a frontpage node would be selected as `promoted to frontpage` would be limited at best.
2. Sticky at top of list is also a limited use case. If we needed to create a view that includes a frontpage content type we could filter by it's node type instead of this field.

Promoted doesn't make sense for frontpage content type due to it already being a frontpage.

2021-03-19 20:08 UTC, callinmullaney commented on config/install/core.entity_form_display.node.page.default.yml
> +    - entity_browser.browser.image_browser
Switched to our custom Image Browser for two reasons:

1. Its specific to Image Media
2. Prevents projects from needing to override views provided by core

2021-03-19 20:12 UTC, callinmullaney commented on config/install/entity_browser.browser.media_entity_browser_modal.yml
> +  width: '850'
Made this browser consistent with the image browser config. `1070px` is a fixed with an it's too wide for tablet devices.

2021-03-19 20:15 UTC, callinmullaney commented on config/install/views.view.image_entity_browser.yml
> +        field_tags_target_id:
Adding exposed filter for Tags to this view in order to match the general `media browser` view

2021-03-19 20:15 UTC, callinmullaney commented on config/install/views.view.video_entity_browser.yml
> +        field_tags_target_id:
Adding exposed filter for Tags to this view in order to match the general media browser view

2021-06-17 12:55 UTC, americkson commented on config/install/entity_browser.browser.media_entity_browser_modal.yml
> +  width: '850'
Set both width and height to `''` (nothing) then we have a nice consistent window that opens on all screens.

2021-06-17 12:55 UTC, americkson commented on config/install/entity_browser.browser.image_browser.yml
> +  width: '850'
Set both width and height to `''` (nothing) then we have a nice consistent window that opens on all screens.

2021-06-17 12:56 UTC, americkson requested changes
Just needs a small tweak then this is GTG!

2021-06-28 03:11 UTC, callinmullaney commented on config/install/entity_browser.browser.media_entity_browser_modal.yml
> +  width: '850'
dimensions for this modal have been removed

2021-06-28 03:11 UTC, callinmullaney commented on config/install/entity_browser.browser.image_browser.yml
> +  width: '850'
dimensions for this modal have been removed

2021-06-28 03:11 UTC, callinmullaney commented
@americkson back to you

2021-07-02 14:49 UTC, americkson approved these changes
:shipit:

2021-07-02 20:42 UTC, merged

2021-09-13 20:03 UTC, dalin- commented
I've vaguely remember having problems in the past with entity browsers in a WYSIWYG.  These required auto-open to be enabled.  Does this apply to Sous?

2021-09-13 22:47 UTC, callinmullaney commented
@dalin- You are correct that this setting needs to be `true` for embedded entity browsers. The entity browsers that are currently in `sous` are meant for reference fields shouldn't trigger auto-open. 

That being said, I do think our entity browser config should be revisited in general. IMO we should have a single `Sous Entity Browsers` view that contains multiple displays for each media type reference and various combinations. Example: It' sometime appropriate for a component to reference an Image AND a video but not and Image/Video/File/Icon/Audio ...etc. 

Then we create a corresponding entity browser for each display and label it by the view name + display name.

2023-01-20 17:18 UTC, fkbender commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-distro/releases/tag/4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: