feat: Better text formatting
fourkitchens/sous-drupal-distro pull request #28
Opened 2021-03-19 19:19 UTC by callinmullaney

### Purpose:
- Improve default configuration for all text formats to be more purposeful. 
- Replace the `Upload Image` widget with embedded media Image with an entity browser
- Configure `Restricted Html` filter for specific use case that allow for limited formatting. Bold, Italics, Link for simple components like cards and Page intro text.
- Add another image based entity browser that is configured with an iframe instead of a modal. This is specifically for embedded media support. 

### Testing:
- [ ] Install Sous and verify the config changes in this PR import without errors.
- [ ]

2021-07-02 17:41 UTC, americkson commented
This "working" as expected from the testing steps but there seems to be an unnecessary step in selecting an image. Upon clicking the "e" Icon, I get this:

<img width="884" alt="Screen Shot 2021-07-02 at 12 34 17 PM" src="https://user-images.githubusercontent.com/545638/124310634-15788600-db32-11eb-98e1-e62ae45eed8b.png">

Which I have the click the 'Select Images' link. Then I get the actual image browser:

<img width="849" alt="Screen Shot 2021-07-02 at 12 34 27 PM" src="https://user-images.githubusercontent.com/545638/124310699-30e39100-db32-11eb-9d48-9c40460fef71.png">

I wonder if we should have a different  image browser configuration for this use case?

The only other thing is I wonder if we can replace that default 'E' icon to at least be an "I" OR we add a hook install step to get an icon that represents embedding an image and have it there by default? We could separate that out as a different issue too.

It will be good to get the entity browser fixes merged in (different issue) then explore what it might take to get that extra step out of the process.

2021-07-02 17:41 UTC, americkson requested changes
See post above. Let's discuss at some point soon.

2021-07-11 08:56 UTC, callinmullaney commented on config/install/entity_browser.browser.image_browser_embedded.yml
> +  auto_open: true
@americkson This auto-open setting should be skipping that extra step of `select image(s)`. It's doing it for me on my end. Can you verify this setting is active for the `Image Browser (Embedded)` entity browser?

2021-07-11 09:00 UTC, callinmullaney commented
@americkson Currently, the `E` icon cannot be changed and remain customized across environments. The problem is the customized icon is stored as a managed file and not something exportable. This is a known issue : https://www.drupal.org/project/embed/issues/2824110#comment-13055494 

Should I include this patch in this PR and upload a custom icon or should we wait until this is fully tested and merged?

2021-09-15 01:40 UTC, ccjjmartin approved these changes
@callinmullaney We can revert my change out if you want but when I reviewed this I noticed that no images I embedded were actually showing.  When I dug into it I found that there is a separate text filter that you have to enable in order for the embedded images to be rendered.  So I enabled it and the images are now showing for me (rather than having the html `<drupal-entity ...` in the rendered output of the page.  It could be due to the fact that I recently updated a lot of modules in other PRs so probably a new "feature".  Anyway, after that one change this PR looks good to me :+1:

2021-09-15 01:41 UTC, ccjjmartin commented on config/install/entity_browser.browser.image_browser_embedded.yml
> +  auto_open: true
It is skipping that step for me when I tried it, I would call this one resolved.

2021-09-15 01:43 UTC, ccjjmartin commented
@americkson I think Callin's approach here of letting each site replace the E icon is acceptable and would call this one ready to merge since it has a lot of good stuff.  If we want the E icon changed let's do that in a follow up PR?

2021-09-17 22:24 UTC, americkson approved these changes

2021-09-20 13:38 UTC, merged

2023-01-20 17:18 UTC, fkbender commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-distro/releases/tag/4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: