feat: Admin user/role defaults
fourkitchens/sous-drupal-distro pull request #34
Opened 2021-06-13 16:19 UTC by callinmullaney

### Purpose:
- Statically set the install form so `superuser` is used. This is a security measure as "admin" or "administrator" is typically used for sites and changing this prevents hacking attempts.
- Unchecks "send email notifications" from the install form and sets the default country to US
- Creates a `Super User` role during install and sets this role as the administrator role of the site
- User settings update so user accounts cannot be created by anon users by default

### Testing:
- [ ] Install Sous and verify...

2021-06-16 23:27 UTC, americkson commented on sous.install
> +  // Assign user 1 the "administrator" role.
This is a good idea but we should almost take this one step further and delete user 1 on install.

2021-06-16 23:28 UTC, americkson commented on sous.install
> +  // Default user 1 username should be 'webmaster'.
Comment doesn't match the `default_value`

2021-06-16 23:29 UTC, americkson commented on sous.install
> +  // Default site email noreply(at)vardot.com.
Not sure we should set this default. I'd skip this one.

2021-06-16 23:29 UTC, americkson commented on sous.install
> +  $form['site_information']['site_name']['#attributes']['placeholder'] = t('My Official Site Name');
Not sure we should set this default. I'd skip this one.

2021-06-16 23:30 UTC, americkson commented on sous.install
> +  $form['admin_account']['account']['mail']['#default_value'] = 'superuser@emulsify.info';
We shouldn't set this as a default. If someone DOES leave the default and doesn't remember the password they could be locked out of an install.

2021-06-16 23:31 UTC, americkson requested changes
Good addition for some tighter security on install. Just need a couple tweaks.

2021-06-28 02:49 UTC, callinmullaney commented on sous.install
> +  // Assign user 1 the "administrator" role.
I went ahead and added `$user->block();` to disable user 1 by default. I'll make a note in the readme that we should create a separate user for admin purposes (not user #1) and ideally use drush to access the site locally.

2021-06-28 02:51 UTC, callinmullaney commented
@americkson Comments addressed and added a block to usrr #1 by default 👍

2021-07-02 18:51 UTC, americkson commented on sous.install
> +  // Assign user 1 the "administrator" role.
Went through the install process here and `superuser` IS `user/1`. And you can still log out and log back in as this user so essentially it's not much different other than forcing the the name `superuser` as the primary admin upon install. I think we need a post install process to remove or disable `user/1` and this `superuser` should be `user/2` or something like that. Might need to work with this one a bit more.

2021-07-02 18:56 UTC, americkson commented
Looks like we might need to work though this one a bit more to make sure we `user/1` is not being used.

2021-07-11 08:12 UTC, callinmullaney commented on sous.install
> +  // Assign user 1 the "administrator" role.
@americkson I went ahead and implemented a post-install step to make sure user/1 is blocked and a user/2 is created with the appropriate permissions. 
1. `superuser_1` is created as the maintenance account during the install. The username is statically set and a password is randomly generated. This password doesn't need to be set or seen by the user as this account will be immediately blocked.
2. Post install step is fired and user/1 is blocked.
3. Post install creates user/2 (`superuser`) and assigns them to the `superuser` user role.
4. user/2 password is randomly generated and displayed as a message once the installation is complete. At this point a dev will capture this one-time-viewed password and save it to a 1pass or something.
5. If the password isn't properly captured or is forgotten the site is still accessible by running `lando drush user:login --uid=2`

2021-09-03 14:56 UTC, ccjjmartin commented on sous.install
> +  // Assign user 1 the "administrator" role.
@callinmullaney I like that we aren't using `admin` as the user name here, technically `superuser` is easily guessable too.  If we are really going for security here we would go with something like "Captain Kirk".

I would recommend that if we are going to block user 1 by default (which is a good idea) that we should include a line in one of our `rebuild` scripts that unblocks the user on local development environments.

Should we also consider disabling the `/user/{id}` pages along with this by default?  Not sure if we did this already but most sites don't need Drupal user pages exposed showing their user name (easy to guess the id from that).

I don't see the need for creating a user 2 because we can unblock 1 within some `rebuild` scripts.

2021-09-03 15:42 UTC, ccjjmartin commented on sous.install
> +  // Assign user 1 the "administrator" role.
@callinmullaney I am going to proceed with the changes we talked about in Slack :+1:

2021-09-03 22:31 UTC, ccjjmartin approved these changes
@americkson I pinged Callin on this one earlier today and we came up with:

My todo list was:
1. Disable user pages
2. Rename user 2 to `sous_chef` instead of `superuser` (easily guessable)
3. Unblock user 1 on the `rebuild` scripts

And here is what I actually did:
1. The permission that controls this was already set by default in Sous so nothing was needed.
2. Pushed up the name change to this PR
3. Separate PR in the project repo for the rebuild script update: https://github.com/fourkitchens/sous-drupal-project/pull/37

I fixed a few more things in the other repo for `npm versus yarn` which we standardized as a company a while back and since we are now requiring PHP 7.4 everyone needs to be running composer commands through lando so I added `lando` in front of `composer install` to prevent failures on the rebuild script due to PHP version.

I am giving this an approval but since you commented on it we won't merge until you also approve.

2021-09-17 22:21 UTC, americkson approved these changes

2021-09-20 13:42 UTC, merged

2023-01-20 17:18 UTC, fkbender commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-distro/releases/tag/4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: