Update README.md
fourkitchens/sous-drupal-distro pull request #57
Opened 2022-02-09 15:58 UTC by Gregg-Hendrix

Updated the Readme with current instructions, regarding `composer update` and gave instructions for file location.

2022-02-10 20:29 UTC, callinmullaney requested changes
@Gregg-Hendrix I'd actually like to stage this documentation change for the 4.x release. This will become the new default branch for this repository when ready. Can you update this line to say `4.x` instead of `2.x` ??

2022-02-11 14:10 UTC, Gregg-Hendrix commented
> @Gregg-Hendrix I'd actually like to stage this documentation change for the 4.x release. This will become the new default branch for this repository when ready. Can you update this line to say `4.x` instead of `2.x` ??

@callinmullaney Thank you Callin! It has now been changed :)

2022-02-14 22:57 UTC, callinmullaney approved these changes

2022-02-14 22:58 UTC, merged

2023-01-20 17:17 UTC, fkbender commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/fourkitchens/sous-drupal-distro/releases/tag/4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: